/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as FondsenRouteImport } from './routes/fondsen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasussenRouteImport } from './routes/casussen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FondsenLamaRouteImport } from './routes/fondsen.lama'
import { Route as FondsenLacunaRouteImport } from './routes/fondsen.lacuna'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const FondsenRoute = FondsenRouteImport.update({
  id: '/fondsen',
  path: '/fondsen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasussenRoute = CasussenRouteImport.update({
  id: '/casussen',
  path: '/casussen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FondsenLamaRoute = FondsenLamaRouteImport.update({
  id: '/lama',
  path: '/lama',
  getParentRoute: () => FondsenRoute,
} as any)
const FondsenLacunaRoute = FondsenLacunaRouteImport.update({
  id: '/lacuna',
  path: '/lacuna',
  getParentRoute: () => FondsenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casussen': typeof CasussenRoute
  '/contact': typeof ContactRoute
  '/fondsen': typeof FondsenRouteWithChildren
  '/investments': typeof InvestmentsRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fondsen/lacuna': typeof FondsenLacunaRoute
  '/fondsen/lama': typeof FondsenLamaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casussen': typeof CasussenRoute
  '/contact': typeof ContactRoute
  '/fondsen': typeof FondsenRouteWithChildren
  '/investments': typeof InvestmentsRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fondsen/lacuna': typeof FondsenLacunaRoute
  '/fondsen/lama': typeof FondsenLamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casussen': typeof CasussenRoute
  '/contact': typeof ContactRoute
  '/fondsen': typeof FondsenRouteWithChildren
  '/investments': typeof InvestmentsRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fondsen/lacuna': typeof FondsenLacunaRoute
  '/fondsen/lama': typeof FondsenLamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casussen'
    | '/contact'
    | '/fondsen'
    | '/investments'
    | '/over-ons'
    | '/sitemap.xml'
    | '/fondsen/lacuna'
    | '/fondsen/lama'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casussen'
    | '/contact'
    | '/fondsen'
    | '/investments'
    | '/over-ons'
    | '/sitemap.xml'
    | '/fondsen/lacuna'
    | '/fondsen/lama'
  id:
    | '__root__'
    | '/'
    | '/casussen'
    | '/contact'
    | '/fondsen'
    | '/investments'
    | '/over-ons'
    | '/sitemap.xml'
    | '/fondsen/lacuna'
    | '/fondsen/lama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasussenRoute: typeof CasussenRoute
  ContactRoute: typeof ContactRoute
  FondsenRoute: typeof FondsenRouteWithChildren
  InvestmentsRoute: typeof InvestmentsRoute
  OverOnsRoute: typeof OverOnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondsen': {
      id: '/fondsen'
      path: '/fondsen'
      fullPath: '/fondsen'
      preLoaderRoute: typeof FondsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casussen': {
      id: '/casussen'
      path: '/casussen'
      fullPath: '/casussen'
      preLoaderRoute: typeof CasussenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondsen/lama': {
      id: '/fondsen/lama'
      path: '/lama'
      fullPath: '/fondsen/lama'
      preLoaderRoute: typeof FondsenLamaRouteImport
      parentRoute: typeof FondsenRoute
    }
    '/fondsen/lacuna': {
      id: '/fondsen/lacuna'
      path: '/lacuna'
      fullPath: '/fondsen/lacuna'
      preLoaderRoute: typeof FondsenLacunaRouteImport
      parentRoute: typeof FondsenRoute
    }
  }
}

interface FondsenRouteChildren {
  FondsenLacunaRoute: typeof FondsenLacunaRoute
  FondsenLamaRoute: typeof FondsenLamaRoute
}

const FondsenRouteChildren: FondsenRouteChildren = {
  FondsenLacunaRoute: FondsenLacunaRoute,
  FondsenLamaRoute: FondsenLamaRoute,
}

const FondsenRouteWithChildren =
  FondsenRoute._addFileChildren(FondsenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasussenRoute: CasussenRoute,
  ContactRoute: ContactRoute,
  FondsenRoute: FondsenRouteWithChildren,
  InvestmentsRoute: InvestmentsRoute,
  OverOnsRoute: OverOnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
